services:
    db:
        image: postgis/postgis:15-3.3
        environment:
            POSTGRES_DB: ${DJANGO_DATABASE_NAME}
            POSTGRES_USER: ${DJANGO_DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DJANGO_DATABASE_USERNAME} -d ${DJANGO_DATABASE_NAME}" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    redis:
        image: redis:7.2-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        env_file:
            .env
        command: redis-server --requirepass ${REDIS_PASSWORD}
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
            interval: 10s
            timeout: 3s
            retries: 5
            start_period: 30s

volumes:
    postgres_data:
    redis_data:
