services:
    db:
        image: postgis/postgis:15-3.3
        environment:
            POSTGRES_DB: ${DJANGO_DATABASE_NAME}
            POSTGRES_USER: ${DJANGO_DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
        ports:
            - "${DJANGO_DATABASE_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7.2-alpine
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis_data:/data
        env_file:
            .env
        command: redis-server --requirepass ${REDIS_PASSWORD}


    gis-tools:
        image: ghcr.io/osgeo/gdal:ubuntu-small-latest
        volumes:
            - ./data:/data
            - ./shared-libs:/shared-libs
        command: |
            sh -c "
              mkdir -p /shared-libs
              cp /usr/lib/x86_64-linux-gnu/libgdal.so* /shared-libs/
              cp /usr/lib/x86_64-linux-gnu/libgeos*.so* /shared-libs/

              cd /shared-libs
              ln -sf libgdal.so.37.3.12.0 libgdal.so
              ln -sf libgeos_c.so.1.18.1 libgeos_c.so
              ln -sf libgeos.so.3.12.1 libgeos.so

              ls -la /shared-libs/
              tail -f /dev/null
            "
        ports:
            - "${GIS_PORT}:8080"

volumes:
    postgres_data:
    redis_data:
