# Generated by Django 5.2.6 on 2025-09-14 13:27

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SightingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("location_name", models.CharField(max_length=200)),
                (
                    "location_point",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Location coordinates", srid=4326
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sighted_by", models.CharField(max_length=255)),
                ("sighted_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["location_name"],
            },
        ),
        migrations.CreateModel(
            name="SightingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "map_center",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(-4.0, 54.5, srid=4326),
                        help_text="Map center point",
                        srid=4326,
                    ),
                ),
                ("zoom_level", models.IntegerField(default=6, help_text="Initial zoom level")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
